teleop_twist_joy:
  ros__parameters:
    axis_linear:
      x: 1  # Left stick vertical
      y: 0  # Left stick horizontal
      z: -1  # Disabled
    
    scale_linear:
      x: 1.0
      y: 1.0
      z: 0.0
    
    scale_linear_turbo:
      x: 2.0
      y: 2.0
      z: 0.0

    axis_angular:
      yaw: 2  # Right stick horizontal
      pitch: -1  # Disabled
      roll: -1  # Disabled
    
    scale_angular:
      yaw: 1.0
      pitch: 0.0
      roll: 0.0
    
    scale_angular_turbo:
      yaw: 2.0
      pitch: 0.0
      roll: 0.0

    enable_button: 0  # A button
    enable_turbo_button: 1  # B button

    require_enable_button: false
